stages:
  - build
  - test

variables:
  # Set the version of .NET SDK you're using (e.g., 6.0 or 7.0)
  DOTNET_VERSION: "9.0.100"

before_script:
  - apt-get update && apt-get install -y wget curl
  - wget https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install -y dotnet-sdk-$DOTNET_VERSION

build:
  stage: build
  script:
    - echo "Restoring project dependencies..."
    - dotnet restore
    - echo "Building project..."
    - dotnet build --configuration Release

test:
  stage: test
  script:
    - echo "Running unit tests..."
    - dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"
  artifacts:
    paths:
      - test-results.trx
    reports:
      junit: test-results.trx
  when: always
